### ISSUE TITLE
"Too many values to unpack"

### ISSUE THREAD

**Issue by Hk-tang** [awwong1/sotorrent-sqlite3#1]
When running this program to get an updated version of the SOTorrent database I encountered an error. "Too many values to unpack" when writing the PostVersion table. It seems that in version: Version 2019-03-17 of the SOTorrent data they added a column to both PostVersion and PostBlockVersion. I forked the repo and am working on fixing this and seeing if there are other issues that requires an update.

**Comment by Hk-tang** [comment]
The PostReferenceGH table remove the PostTypeId.

**Comment by awwong1** [comment]
https://github.com/awwong1/sotorrent-sqlite3/pull/2
